Animated number counter
SSGSA-dev/ssgsa-application-portal pull request #37
Opened 2021-08-28 18:00 UTC by ayaankhan98

closes #36

2021-08-28 18:03 UTC, ayaankhan98 commented on components/Counter.js
> +          <CountUp start={0} end={119} duration={1} />+ <span style={{fontSize: "40px"}}>Scholars</span>
Just add a `+` sign there so decreased 22 to 20, 100 to 99 and 120 to 199

2021-08-29 07:57 UTC, roshnet requested changes
@ayaankhan98 thanks for the changes. It looks good on desktop, however doesn't fit on mobile devices. Please check screenshot -

![image](https://user-images.githubusercontent.com/40719199/131243010-fc3a7452-7a68-44a1-a530-b2a458df9c20.png)

2021-08-29 08:48 UTC, ayaankhan98 commented
I think this looks fine? isn't?
![Screenshot_20210829_141753](https://user-images.githubusercontent.com/43348292/131244515-311e06ba-a111-40fa-9e02-272ffe98bb23.png)

2021-08-29 09:05 UTC, ayaankhan98 commented
A better way to do this is show count animation only when Counter component comes into picture (meaning in viewport). The way it's working right now is it starts as soon as the web page loads, and may be it will not make any sense because it will give static view as earlier if the user does not scrolls to that component in mobile view on load or in desktop mode (if component is out of viewport onload).

A simple solution to this is to create a custom hook to check the visibility of a component in view port or may be track the window scroll position and check if your div comes into picture or not (Perhaps are other better ways to achieve the same).

May be someone else can improve based on this.

2021-08-29 09:31 UTC, roshnet commented
> @roshnet 
> I think this looks fine? isn't?
> ![Screenshot_20210829_141753](https://user-images.githubusercontent.com/43348292/131244515-311e06ba-a111-40fa-9e02-272ffe98bb23.png)
> 

@ayaankhan98 yes, this is perfect.

2021-08-29 09:37 UTC, roshnet commented
> A better way to do this is show count animation only when Counter component comes into picture (meaning in viewport). The way it's working right now is it starts as soon as the web page loads, and may be it will not make any sense because it will give static view as earlier if the user does not scrolls to that component in mobile view on load or in desktop mode (if component is out of viewport onload).
> 
> A simple solution to this is to create a custom hook to check the visibility of a component in view port or may be track the window scroll position and check if your div comes into picture or not (Perhaps are other better ways to achieve the same).
> 
> May be someone else can improve based on this.

Good idea! Although since I think the current PR is good enough, this enhancement can be implemented in another issue.

That said, feel free to go ahead an update the PR if you've got an idea, thanks!

2021-08-29 09:52 UTC, ayaankhan98 commented
> Good idea! Although since I think the current PR is good enough, this enhancement can be implemented in another issue.

I think this is good, may be someone else will do this.

2021-08-30 05:13 UTC, himanshuvarandani commented
@ayaankhan98 changes looks good, but this doesn't fit for tablet view and large screens (768px < size < 1200px).
Check screenshots:

![image](https://user-images.githubusercontent.com/44665645/131287484-165b07f1-57de-42ea-8076-40b5eb1370b5.png)

![image](https://user-images.githubusercontent.com/44665645/131287515-0786d3f7-4537-4f09-b57b-7a84730c4864.png)


I can suggest some changes: 
-  decrease the size for sm and md screens 
-  put all 3 counters in the same line and write all counter label in below line (check the second screenshot you gave in the issue #36)

2021-08-30 08:50 UTC, ayaankhan98 commented
> @ayaankhan98 changes looks good, but this doesn't fit for tablet view and large screens (768px < size < 1200px).

Hope now this looks good over all commonly used resolutions.

2021-08-30 13:31 UTC, pnijhara commented
@roshnet if it is ready to merge then you can merge it. You can also open the new issue related to scrolling that Ayan pointed out.

2021-08-30 13:38 UTC, merged