Floating news added #41
SSGSA-dev/ssgsa-application-portal pull request #51
Opened 2021-09-26 13:48 UTC by Ahrazshamim

A floating news section was added.

2021-09-26 14:07 UTC, himanshuvarandani approved these changes

2021-09-26 15:44 UTC, pnijhara requested changes

2021-09-26 15:44 UTC, pnijhara commented on pages/index.js
> +  <marquee>
Give proper indentation.

2021-09-26 15:44 UTC, pnijhara commented on pages/index.js
> +    <p> SSGSA results (2021-2022) annonced </p>
This should be "announced".

2021-09-27 12:54 UTC, Ahrazshamim commented on pages/index.js
> +    <p> SSGSA results (2021-2022) annonced </p>
updated, please review

2021-09-28 05:12 UTC, pnijhara approved these changes
This looks good. Thank you for the PR.

2021-09-28 05:12 UTC, merged